# .github/workflows/release.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3-beta, etc.

jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows builds
          - goos: windows
            goarch: amd64
            runner: windows-latest
            binary_suffix: '.exe'
            build_tags: 'bundled'
            asset_name: 'timekeeper_bundled-windows-amd64.exe'
          - goos: windows
            goarch: amd64
            runner: windows-latest
            binary_suffix: '.exe'
            build_tags: ''
            asset_name: 'timekeeper-windows-amd64.exe'
          - goos: windows
            goarch: arm64
            runner: windows-latest
            binary_suffix: '.exe'
            build_tags: ''
            asset_name: 'timekeeper-windows-arm64.exe'

          # Linux builds
          - goos: linux
            goarch: amd64
            runner: ubuntu-latest
            binary_suffix: ''
            build_tags: ''
            asset_name: 'timekeeper-linux-amd64'
          - goos: linux
            goarch: arm64
            runner: ubuntu-latest
            binary_suffix: ''
            build_tags: ''
            asset_name: 'timekeeper-linux-arm64'

          # macOS builds
          - goos: darwin
            goarch: amd64
            runner: macos-latest
            binary_suffix: ''
            build_tags: ''
            asset_name: 'timekeeper-macos-amd64'
          - goos: darwin
            goarch: arm64
            runner: macos-latest
            binary_suffix: ''
            build_tags: ''
            asset_name: 'timekeeper-macos-arm64'

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binary (Linux/macOS)
      if: matrix.goos != 'windows'
      run: |
        if [ -n "${{ matrix.build_tags }}" ]; then
          go build -tags "${{ matrix.build_tags }}" \
            -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" \
            -o ${{ matrix.asset_name }} .
        else
          go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" \
            -o ${{ matrix.asset_name }} .
        fi

    
    - name: Download ExifTool (Windows bundled only)
      if: matrix.runner == 'windows-latest'
      shell: pwsh
      run: |
        Write-Host "Downloading ExifTool for Windows..."
        $exiftoolVersion = "13.34"
        
        # Create directory structure
        New-Item -ItemType Directory -Force -Path "bin\windows"
        
        # Download ExifTool
        $url = "https://exiftool.org/exiftool-$exiftoolVersion`_64.zip"
        Write-Host "Downloading from: $url"
        Invoke-WebRequest -Uri $url -OutFile "exiftool-windows.zip"
        
        # Extract
        Expand-Archive -Path "exiftool-windows.zip" -DestinationPath "temp-exiftool" -Force
        
        # Navigate into the extracted folder
        $extractedFolder = Get-ChildItem "temp-exiftool" -Directory | Select-Object -First 1
        Write-Host "Found extracted folder: $($extractedFolder.Name)"
        $exiftoolPath = $extractedFolder.FullName
        
        # Find and copy the executable
        if (Test-Path "$exiftoolPath\exiftool(-k).exe") {
            Write-Host "Found exiftool(-k).exe, copying as exiftool.exe"
            Copy-Item "$exiftoolPath\exiftool(-k).exe" "bin\windows\exiftool.exe"
        } elseif (Test-Path "$exiftoolPath\exiftool.exe") {
            Write-Host "Found exiftool.exe"
            Copy-Item "$exiftoolPath\exiftool.exe" "bin\windows\exiftool.exe"
        } else {
            Write-Host "Looking for ExifTool executable in $exiftoolPath..."
            Get-ChildItem $exiftoolPath -Filter "*exiftool*" -File
            exit 1
        }
        
        # Copy exiftool_files directory if it exists
        if (Test-Path "$exiftoolPath\exiftool_files") {
            Write-Host "Copying exiftool_files directory"
            Copy-Item -Path "$exiftoolPath\exiftool_files" -Destination "bin\windows\" -Recurse
        } else {
            Write-Host "No exiftool_files directory found"
            Write-Host "Contents of $exiftoolPath :"
            Get-ChildItem $exiftoolPath
        }
        
        # Clean up
        Remove-Item -Path "temp-exiftool" -Recurse -Force
        Remove-Item -Path "exiftool-windows.zip" -Force
        

    - name: Build binary (Windows)
      if: matrix.goos == 'windows'
      shell: pwsh
      run: |
        if ($env:BUILD_TAGS -ne "") {
            go build -tags $env:BUILD_TAGS -ldflags "-s -w -X main.version=$env:VERSION" -o $env:ASSET_NAME .
        } else {
            go build -ldflags "-s -w -X main.version=$env:VERSION" -o $env:ASSET_NAME .
        }
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
        ASSET_NAME: ${{ matrix.asset_name }}
        BUILD_TAGS: ${{ matrix.build_tags }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases
    steps:
      - uses: actions/checkout@v5

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.VERSION, 'beta') || contains(steps.version.outputs.VERSION, 'alpha') || contains(steps.version.outputs.VERSION, 'rc') }}
          files: |
            artifacts/*/timekeeper-*
          token: ${{ secrets.TIMEKEEPER }}